### ISSUE TITLE
Automated Docker Builds

### ISSUE THREAD

**Issue by Huskydog9988** [wikipedia-bot/wikipedia-bot-canary#25]
**Is your feature request related to a problem? Please describe.**
Currently, to deploy Wikipedia Bot Canary the docker image is built and pushed manually by hand to Docker Hub.

**Describe the solution you'd like**
Have GitHub Actions automatically build and push Docker images on push to master and releases.

**Describe alternatives you've considered**
Could use an outside ci tools like Travis, or use Docker Hub's automated image builder.

**Comment by MeerBiene** [comment]
Notes:
- use [buildah](https://buildah.io)

**Comment by MeerBiene** [comment]
added in e5f0bf318f6a26928ab0334e7cf078e94c15b0d8
